"""Validate and apply structured patches generated by Groq."""
from __future__ import annotations

import io
import re
import zipfile

SEVERE = {"critical", "high"}


def validate_groq_patches(files, findings, patches):
    if not isinstance(patches, list):
        raise ValueError("Groq response must contain a patches array")
    validated = []
    seen = set()
    for raw in patches:
        if not isinstance(raw, dict) or not isinstance(raw.get("finding_index"), int):
            continue
        index = raw["finding_index"]
        if index < 0 or index >= len(findings) or index in seen:
            continue
        finding = findings[index]
        name, number = finding["file"], finding["line"]
        lines = files.get(name, "").splitlines()
        replacement = raw.get("replacement")
        imports = raw.get("required_imports", [])
        if raw.get("file") != name or raw.get("line") != number or number < 1 or number > len(lines):
            continue
        if not isinstance(replacement, str) or not replacement.strip() or "\n" in replacement or "\r" in replacement or len(replacement) > 1_000:
            continue
        if not isinstance(imports, list) or len(imports) > 5 or not all(isinstance(item, str) and re.fullmatch(r"[A-Za-z_][A-Za-z0-9_.]*", item) for item in imports):
            continue
        seen.add(index)
        validated.append({
            "id": f"groq-fix-{index}",
            "finding_index": index,
            "type": finding["type"],
            "title": finding["title"],
            "severity": finding["severity"],
            "file": name,
            "line": number,
            "requires_approval": finding["severity"] in SEVERE,
            "explanation": str(raw.get("explanation", "Groq-generated remediation"))[:500],
            "before": "Potential secret detected; value redacted" if finding["type"] == "hardcoded_secret" else lines[number - 1].strip(),
            "after": replacement.strip(),
            "_raw_before": lines[number - 1],
            "_raw_after": replacement,
            "_required_imports": imports,
        })
    return validated


def apply_automatic_fixes(files, patches):
    selected = [item for item in patches if not item["requires_approval"]]
    fixed = dict(files)
    for name in {item["file"] for item in selected}:
        original = fixed[name]
        lines = original.splitlines()
        file_patches = [item for item in selected if item["file"] == name]
        for item in file_patches:
            index = item["line"] - 1
            if lines[index] == item["_raw_before"]:
                lines[index] = item["_raw_after"]
        imports = {module for item in file_patches for module in item["_required_imports"]}
        for module in sorted(imports, reverse=True):
            statement = f"import {module}"
            if not any(line == statement or line.startswith(f"import {module},") for line in lines):
                lines.insert(0, statement)
        fixed[name] = "\n".join(lines) + ("\n" if original.endswith("\n") else "")
    return fixed, selected


def zip_files(files):
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as archive:
        for name, content in sorted(files.items()):
            archive.writestr(name, content)
    return output.getvalue()
